-- 코드를 입력하세요

SELECT YEAR(os.SALES_DATE) as YEAR, MONTH(os.SALES_DATE) as MONTH, COUNT(distinct os.USER_ID) AS "PURCHASED_USERS", ROUND(COUNT(distinct os.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) as "PUCHASED_RATIO"
FROM ONLINE_SALE as os
JOIN USER_INFO as ui ON os.USER_ID = ui.USER_ID
WHERE YEAR(ui.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;